//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: Header.proto
//
//package com.iscas.protobuf;
//
//public final class Header {
//  private Header() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  public interface HeadOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:Head)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>required fixed32 length = 1;</code>
//     */
//    boolean hasLength();
//    /**
//     * <code>required fixed32 length = 1;</code>
//     */
//    int getLength();
//
//    /**
//     * <code>required fixed32 messageType = 2;</code>
//     */
//    boolean hasMessageType();
//    /**
//     * <code>required fixed32 messageType = 2;</code>
//     */
//    int getMessageType();
//  }
//  /**
//   * Protobuf type {@code Head}
//   */
//  public  static final class Head extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:Head)
//      HeadOrBuilder {
//  private static final long serialVersionUID = 0L;
//    // Use Head.newBuilder() to construct.
//    private Head(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private Head() {
//      length_ = 0;
//      messageType_ = 0;
//    }
//
//    @Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return this.unknownFields;
//    }
//    private Head(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      if (extensionRegistry == null) {
//        throw new NullPointerException();
//      }
//      int mutable_bitField0_ = 0;
//      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//          com.google.protobuf.UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            default: {
//              if (!parseUnknownField(
//                  input, unknownFields, extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//            case 13: {
//              bitField0_ |= 0x00000001;
//              length_ = input.readFixed32();
//              break;
//            }
//            case 21: {
//              bitField0_ |= 0x00000002;
//              messageType_ = input.readFixed32();
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return com.iscas.protobuf.Header.internal_static_Head_descriptor;
//    }
//
//    protected FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return com.iscas.protobuf.Header.internal_static_Head_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              com.iscas.protobuf.Header.Head.class, com.iscas.protobuf.Header.Head.Builder.class);
//    }
//
//    private int bitField0_;
//    public static final int LENGTH_FIELD_NUMBER = 1;
//    private int length_;
//    /**
//     * <code>required fixed32 length = 1;</code>
//     */
//    public boolean hasLength() {
//      return ((bitField0_ & 0x00000001) == 0x00000001);
//    }
//    /**
//     * <code>required fixed32 length = 1;</code>
//     */
//    public int getLength() {
//      return length_;
//    }
//
//    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
//    private int messageType_;
//    /**
//     * <code>required fixed32 messageType = 2;</code>
//     */
//    public boolean hasMessageType() {
//      return ((bitField0_ & 0x00000002) == 0x00000002);
//    }
//    /**
//     * <code>required fixed32 messageType = 2;</code>
//     */
//    public int getMessageType() {
//      return messageType_;
//    }
//
//    private byte memoizedIsInitialized = -1;
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      if (!hasLength()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      if (!hasMessageType()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (((bitField0_ & 0x00000001) == 0x00000001)) {
//        output.writeFixed32(1, length_);
//      }
//      if (((bitField0_ & 0x00000002) == 0x00000002)) {
//        output.writeFixed32(2, messageType_);
//      }
//      unknownFields.writeTo(output);
//    }
//
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (((bitField0_ & 0x00000001) == 0x00000001)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeFixed32Size(1, length_);
//      }
//      if (((bitField0_ & 0x00000002) == 0x00000002)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeFixed32Size(2, messageType_);
//      }
//      size += unknownFields.getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @Override
//    public boolean equals(final Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof com.iscas.protobuf.Header.Head)) {
//        return super.equals(obj);
//      }
//      com.iscas.protobuf.Header.Head other = (com.iscas.protobuf.Header.Head) obj;
//
//      boolean result = true;
//      result = result && (hasLength() == other.hasLength());
//      if (hasLength()) {
//        result = result && (getLength()
//            == other.getLength());
//      }
//      result = result && (hasMessageType() == other.hasMessageType());
//      if (hasMessageType()) {
//        result = result && (getMessageType()
//            == other.getMessageType());
//      }
//      result = result && unknownFields.equals(other.unknownFields);
//      return result;
//    }
//
//    @Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      if (hasLength()) {
//        hash = (37 * hash) + LENGTH_FIELD_NUMBER;
//        hash = (53 * hash) + getLength();
//      }
//      if (hasMessageType()) {
//        hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
//        hash = (53 * hash) + getMessageType();
//      }
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static com.iscas.protobuf.Header.Head parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.iscas.protobuf.Header.Head parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.iscas.protobuf.Header.Head parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.iscas.protobuf.Header.Head parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.iscas.protobuf.Header.Head parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.iscas.protobuf.Header.Head parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.iscas.protobuf.Header.Head parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.iscas.protobuf.Header.Head parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.iscas.protobuf.Header.Head parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static com.iscas.protobuf.Header.Head parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.iscas.protobuf.Header.Head parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.iscas.protobuf.Header.Head parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(com.iscas.protobuf.Header.Head prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @Override
//    protected Builder newBuilderForType(
//        BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code Head}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:Head)
//        com.iscas.protobuf.Header.HeadOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return com.iscas.protobuf.Header.internal_static_Head_descriptor;
//      }
//
//      protected FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return com.iscas.protobuf.Header.internal_static_Head_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                com.iscas.protobuf.Header.Head.class, com.iscas.protobuf.Header.Head.Builder.class);
//      }
//
//      // Construct using com.iscas.protobuf.Header.Head.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      public Builder clear() {
//        super.clear();
//        length_ = 0;
//        bitField0_ = (bitField0_ & ~0x00000001);
//        messageType_ = 0;
//        bitField0_ = (bitField0_ & ~0x00000002);
//        return this;
//      }
//
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return com.iscas.protobuf.Header.internal_static_Head_descriptor;
//      }
//
//      public com.iscas.protobuf.Header.Head getDefaultInstanceForType() {
//        return com.iscas.protobuf.Header.Head.getDefaultInstance();
//      }
//
//      public com.iscas.protobuf.Header.Head build() {
//        com.iscas.protobuf.Header.Head result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      public com.iscas.protobuf.Header.Head buildPartial() {
//        com.iscas.protobuf.Header.Head result = new com.iscas.protobuf.Header.Head(this);
//        int from_bitField0_ = bitField0_;
//        int to_bitField0_ = 0;
//        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
//          to_bitField0_ |= 0x00000001;
//        }
//        result.length_ = length_;
//        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
//          to_bitField0_ |= 0x00000002;
//        }
//        result.messageType_ = messageType_;
//        result.bitField0_ = to_bitField0_;
//        onBuilt();
//        return result;
//      }
//
//      public Builder clone() {
//        return (Builder) super.clone();
//      }
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.setField(field, value);
//      }
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return (Builder) super.clearField(field);
//      }
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return (Builder) super.clearOneof(oneof);
//      }
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, Object value) {
//        return (Builder) super.setRepeatedField(field, index, value);
//      }
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.addRepeatedField(field, value);
//      }
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof com.iscas.protobuf.Header.Head) {
//          return mergeFrom((com.iscas.protobuf.Header.Head)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(com.iscas.protobuf.Header.Head other) {
//        if (other == com.iscas.protobuf.Header.Head.getDefaultInstance()) return this;
//        if (other.hasLength()) {
//          setLength(other.getLength());
//        }
//        if (other.hasMessageType()) {
//          setMessageType(other.getMessageType());
//        }
//        this.mergeUnknownFields(other.unknownFields);
//        onChanged();
//        return this;
//      }
//
//      public final boolean isInitialized() {
//        if (!hasLength()) {
//          return false;
//        }
//        if (!hasMessageType()) {
//          return false;
//        }
//        return true;
//      }
//
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        com.iscas.protobuf.Header.Head parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (com.iscas.protobuf.Header.Head) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//      private int bitField0_;
//
//      private int length_ ;
//      /**
//       * <code>required fixed32 length = 1;</code>
//       */
//      public boolean hasLength() {
//        return ((bitField0_ & 0x00000001) == 0x00000001);
//      }
//      /**
//       * <code>required fixed32 length = 1;</code>
//       */
//      public int getLength() {
//        return length_;
//      }
//      /**
//       * <code>required fixed32 length = 1;</code>
//       */
//      public Builder setLength(int value) {
//        bitField0_ |= 0x00000001;
//        length_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required fixed32 length = 1;</code>
//       */
//      public Builder clearLength() {
//        bitField0_ = (bitField0_ & ~0x00000001);
//        length_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private int messageType_ ;
//      /**
//       * <code>required fixed32 messageType = 2;</code>
//       */
//      public boolean hasMessageType() {
//        return ((bitField0_ & 0x00000002) == 0x00000002);
//      }
//      /**
//       * <code>required fixed32 messageType = 2;</code>
//       */
//      public int getMessageType() {
//        return messageType_;
//      }
//      /**
//       * <code>required fixed32 messageType = 2;</code>
//       */
//      public Builder setMessageType(int value) {
//        bitField0_ |= 0x00000002;
//        messageType_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required fixed32 messageType = 2;</code>
//       */
//      public Builder clearMessageType() {
//        bitField0_ = (bitField0_ & ~0x00000002);
//        messageType_ = 0;
//        onChanged();
//        return this;
//      }
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.setUnknownFields(unknownFields);
//      }
//
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.mergeUnknownFields(unknownFields);
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:Head)
//    }
//
//    // @@protoc_insertion_point(class_scope:Head)
//    private static final com.iscas.protobuf.Header.Head DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new com.iscas.protobuf.Header.Head();
//    }
//
//    public static com.iscas.protobuf.Header.Head getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    @Deprecated public static final com.google.protobuf.Parser<Head>
//        PARSER = new com.google.protobuf.AbstractParser<Head>() {
//      public Head parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return new Head(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<Head> parser() {
//      return PARSER;
//    }
//
//    @Override
//    public com.google.protobuf.Parser<Head> getParserForType() {
//      return PARSER;
//    }
//
//    public com.iscas.protobuf.Header.Head getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_Head_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_Head_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    String[] descriptorData = {
//      "\n\014Header.proto\"+\n\004Head\022\016\n\006length\030\001 \002(\007\022\023" +
//      "\n\013messageType\030\002 \002(\007B\034\n\022com.iscas.protobu" +
//      "fB\006Header"
//    };
//    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
//        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
//          public com.google.protobuf.ExtensionRegistry assignDescriptors(
//              com.google.protobuf.Descriptors.FileDescriptor root) {
//            descriptor = root;
//            return null;
//          }
//        };
//    com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        }, assigner);
//    internal_static_Head_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_Head_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_Head_descriptor,
//        new String[] { "Length", "MessageType", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
